package fr.chauffdoc.outils;

import android.app.*; import android.os.*; import android.content.*; import android.graphics.*; import android.graphics.drawable.*; import android.hardware.*; import android.media.*; import android.text.InputType; import android.view.*; import android.widget.*; import java.util.*;

public class MainActivity extends Activity implements SensorEventListener {
 static final int NAVY=Color.rgb(4,45,88), ORANGE=Color.rgb(255,105,0), GREEN=Color.rgb(8,170,72), RED=Color.rgb(220,48,48), BG=Color.rgb(243,249,253), MUTED=Color.rgb(95,119,150);
 SensorManager sm; Sensor magnetic; ToneGenerator tone; Handler h=new Handler(Looper.getMainLooper()); LinearLayout content; RotorView rotor; TextView field,state; boolean sound=true,vibration=true; final ArrayDeque<Float> samples=new ArrayDeque<>(); float baseline=-1; long lastDetected,lastFeedback;
 int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} GradientDrawable box(int c,float r){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));return d;}
 TextView tv(String s,float z,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(NAVY);if(b)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
 LinearLayout.LayoutParams mp(int w,int hh,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,hh);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}
 Button button(String s,boolean primary){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(16);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setTextColor(primary?Color.WHITE:NAVY);b.setBackground(box(primary?NAVY:Color.rgb(239,246,251),14));return b;}
 @Override public void onCreate(Bundle b){super.onCreate(b);sm=(SensorManager)getSystemService(SENSOR_SERVICE);magnetic=sm.getDefaultSensor(Sensor.TYPE_MAGNETIC_FIELD);tone=new ToneGenerator(AudioManager.STREAM_NOTIFICATION,60);showHome();}
 void shell(boolean home){if(sm!=null)sm.unregisterListener(this);rotor=null;field=null;state=null; LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG); ScrollView sc=new ScrollView(this);sc.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(14),dp(10),dp(14),dp(26)); sc.addView(content,new ScrollView.LayoutParams(-1,-2)); root.addView(sc,new LinearLayout.LayoutParams(-1,0,1)); if(!home){LinearLayout nav=new LinearLayout(this);nav.setPadding(dp(10),dp(6),dp(10),dp(8));nav.setBackgroundColor(NAVY);Button a=button("⌂  Accueil",false),m=button("🧲  Magnetic",false),g=button("⏱  Compteur",false);a.setOnClickListener(v->showHome());m.setOnClickListener(v->showMagnetic());g.setOnClickListener(v->showCounter());nav.addView(a,new LinearLayout.LayoutParams(0,dp(52),1));nav.addView(m,mp(0,dp(52),6,0,0,0));nav.addView(g,mp(0,dp(52),6,0,0,0));root.addView(nav);}setContentView(root);}
 void logo(){ImageView im=new ImageView(this);im.setImageResource(fr.chauffdoc.outils.R.drawable.chauffdoc_logo);im.setScaleType(ImageView.ScaleType.CENTER_INSIDE);content.addView(im,mp(-1,dp(150),0,0,0,8));}
 void heading(String icon,String title,String sub){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(18),dp(12),dp(18),dp(12));card.setBackground(box(Color.WHITE,22));TextView t=tv(icon+"  "+title,24,true);TextView s=tv(sub,14,false);s.setTextColor(MUTED);card.addView(t);card.addView(s,mp(-1,-2,0,5,0,0));content.addView(card,mp(-1,-2,0,0,0,12));}
 void showHome(){shell(true);logo();TextView t=tv("Outils technicien",25,true);t.setGravity(Gravity.CENTER);content.addView(t,mp(-1,-2,0,4,0,18));Button m=button("🧲  Magnetic Tool",true);m.setTextSize(20);m.setOnClickListener(v->showMagnetic());content.addView(m,mp(-1,dp(76),0,0,0,14));Button c=button("⏱  Top compteur gaz",true);c.setTextSize(20);c.setOnClickListener(v->showCounter());content.addView(c,mp(-1,dp(76),0,0,0,12));TextView n=tv("Deux outils Chauff’Doc simples pour accompagner le diagnostic sur le terrain.",14,false);n.setGravity(Gravity.CENTER);n.setTextColor(MUTED);content.addView(n);}
 void showCounter(){shell(false);logo();heading("⏱","Top compteur gaz","Chronomètre automatique pour contrôler une éventuelle variation"); final int[] duration={60},remaining={60};final boolean[] running={false};final Runnable[] tick={null};
  LinearLayout chrono=new LinearLayout(this);chrono.setOrientation(LinearLayout.VERTICAL);chrono.setGravity(Gravity.CENTER);chrono.setPadding(dp(10),dp(12),dp(10),dp(12));chrono.setBackground(box(Color.rgb(235,245,252),18));TextView clock=tv("01:00",54,true);clock.setGravity(Gravity.CENTER);TextView lab=tv("Durée du test",15,false);lab.setTextColor(MUTED);lab.setGravity(Gravity.CENTER);chrono.addView(clock);chrono.addView(lab);content.addView(chrono,mp(-1,-2,0,0,0,10));
  LinearLayout presets=new LinearLayout(this);int[] sec={30,60,120,300};String[] names={"30 s","1 min","2 min","5 min"};Button[] pb=new Button[4];for(int i=0;i<4;i++){pb[i]=button(names[i],i==1);final int ix=i;pb[i].setOnClickListener(v->{if(running[0])return;duration[0]=sec[ix];remaining[0]=sec[ix];clock.setText(time(sec[ix]));for(int j=0;j<4;j++){pb[j].setTextColor(j==ix?Color.WHITE:NAVY);pb[j].setBackground(box(j==ix?ORANGE:Color.rgb(239,246,251),14));}});presets.addView(pb[i],mp(0,dp(54),i==0?0:5,0,0,0));presets.getLayoutParams();((LinearLayout.LayoutParams)pb[i].getLayoutParams()).weight=1;}content.addView(presets,mp(-1,dp(54),0,0,0,10));
  Button start=button("▶  Lancer le contrôle",true);content.addView(start,mp(-1,dp(62),0,0,0,8));Button reset=button("↻  Nouveau contrôle",false);content.addView(reset,mp(-1,dp(56),0,0,0,14));
  LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(16),dp(14),dp(16),dp(16));card.setBackground(box(Color.WHITE,22));TextView rh=tv("▣  Relevé compteur",22,true);card.addView(rh);TextView rs=tv("Saisissez les index du compteur gaz",14,false);rs.setTextColor(MUTED);card.addView(rs,mp(-1,-2,0,2,0,12));LinearLayout fields=new LinearLayout(this);EditText a=input("Ex. 1234.567"),z=input("À relever après le chrono");LinearLayout fa=fieldBox("Index de départ (m³)",a),fz=fieldBox("Index de fin (m³)",z);fields.addView(fa,new LinearLayout.LayoutParams(0,-2,1));fields.addView(fz,mp(0,-2,8,0,0,0));((LinearLayout.LayoutParams)fz.getLayoutParams()).weight=1;card.addView(fields);Button calc=button("▦  Calculer l’écart",false);card.addView(calc,mp(-1,dp(58),0,12,0,0));content.addView(card,mp(-1,-2,0,0,0,14));
  LinearLayout result=new LinearLayout(this);result.setOrientation(LinearLayout.VERTICAL);result.setGravity(Gravity.CENTER);result.setPadding(dp(12),dp(14),dp(12),dp(14));result.setBackground(box(Color.rgb(236,251,241),22));TextView rt=tv("Écart compteur",20,true);TextView rv=tv("0.000 m³",44,true);rv.setTextColor(GREEN);result.addView(rt);result.addView(rv);content.addView(result,mp(-1,-2,0,0,0,12));TextView note=tv("ⓘ Cet outil indique uniquement l’écart au compteur. À utiliser dans le cadre de votre procédure de contrôle gaz.",13,true);note.setTextColor(Color.rgb(20,115,210));note.setPadding(dp(14),dp(12),dp(14),dp(12));note.setBackground(box(Color.rgb(232,246,255),18));content.addView(note);
  tick[0]=new Runnable(){public void run(){if(!running[0])return;remaining[0]--;clock.setText(time(remaining[0]));if(remaining[0]<=0){running[0]=false;start.setText("✓ Contrôle terminé");z.requestFocus();}else h.postDelayed(this,1000);}};
  start.setOnClickListener(v->{if(a.getText().toString().trim().isEmpty()){a.setError("Saisissez l’index de départ");return;}remaining[0]=duration[0];clock.setText(time(remaining[0]));running[0]=true;start.setText("● Contrôle en cours…");h.removeCallbacks(tick[0]);h.postDelayed(tick[0],1000);}); reset.setOnClickListener(v->{running[0]=false;h.removeCallbacks(tick[0]);remaining[0]=duration[0];clock.setText(time(remaining[0]));a.setText("");z.setText("");rv.setText("0.000 m³");start.setText("▶  Lancer le contrôle");}); calc.setOnClickListener(v->{try{double x=Double.parseDouble(a.getText().toString().replace(',','.')),y=Double.parseDouble(z.getText().toString().replace(',','.'));if(y<x){z.setError("Index final inférieur à l’index de départ");return;}rv.setText(String.format(Locale.FRANCE,"%.3f m³",y-x));}catch(Exception e){z.setError("Saisissez les deux index");}});
 }
 EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(16);e.setSingleLine(true);e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);e.setPadding(dp(12),0,dp(12),0);e.setBackground(box(Color.rgb(246,249,252),12));return e;}
 LinearLayout fieldBox(String label,EditText e){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);TextView l=tv(label,14,true);x.addView(l);x.addView(e,mp(-1,dp(58),0,6,0,0));return x;}
 void showMagnetic(){shell(false);logo();heading("🧲","Magnetic Tool","Contrôle simple du circulateur chaudière");LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(16),dp(12),dp(16),dp(16));card.setBackground(box(Color.WHITE,22));rotor=new RotorView(this);card.addView(rotor,new LinearLayout.LayoutParams(-1,dp(250)));state=tv("Approchez le téléphone du circulateur",18,true);state.setGravity(Gravity.CENTER);state.setPadding(dp(8),dp(10),dp(8),dp(10));state.setBackground(box(Color.rgb(235,245,252),16));card.addView(state,mp(-1,-2,0,6,0,10));field=tv("Champ magnétique : -- µT",20,true);field.setGravity(Gravity.CENTER);field.setBackground(box(Color.rgb(238,246,251),16));field.setPadding(dp(8),dp(14),dp(8),dp(14));card.addView(field);TextView info=tv("ⓘ Approchez le haut ou l’arrière du téléphone du circulateur. La roue s’anime lorsqu’une variation magnétique est détectée.",13,false);info.setPadding(dp(12),dp(12),dp(12),dp(12));info.setTextColor(MUTED);card.addView(info,mp(-1,-2,0,10,0,8));LinearLayout opts=new LinearLayout(this);Button s=button("🔊 Son activé",false),v=button("📳 Vibration activée",false);opts.addView(s,new LinearLayout.LayoutParams(0,dp(58),1));opts.addView(v,mp(0,dp(58),8,0,0,0));((LinearLayout.LayoutParams)v.getLayoutParams()).weight=1;s.setOnClickListener(x->{sound=!sound;s.setText(sound?"🔊 Son activé":"🔇 Son coupé");});v.setOnClickListener(x->{vibration=!vibration;v.setText(vibration?"📳 Vibration activée":"Vibration coupée");});card.addView(opts);content.addView(card);TextView note=tv("Aide au diagnostic : une activité magnétique détectée ne confirme pas à elle seule le débit hydraulique du circulateur.",13,false);note.setTextColor(MUTED);note.setPadding(dp(12),dp(12),dp(12),dp(12));content.addView(note);baseline=-1;samples.clear();lastDetected=0;if(magnetic==null){state.setText("Magnétomètre indisponible");state.setTextColor(RED);}else sm.registerListener(this,magnetic,SensorManager.SENSOR_DELAY_GAME);}
 @Override public void onSensorChanged(SensorEvent e){if(e.sensor.getType()!=Sensor.TYPE_MAGNETIC_FIELD||rotor==null||field==null)return;float x=e.values[0],y=e.values[1],z=e.values[2],mag=(float)Math.sqrt(x*x+y*y+z*z);field.setText(String.format(Locale.FRANCE,"Champ magnétique : %.1f µT",mag));samples.addLast(mag);if(samples.size()>28)samples.removeFirst();if(baseline<0)baseline=mag;else baseline=baseline*.985f+mag*.015f;float mean=0;for(float f:samples)mean+=f;mean/=Math.max(1,samples.size());float dev=0;for(float f:samples)dev+=Math.abs(f-mean);dev/=Math.max(1,samples.size());boolean active=samples.size()>12&&(dev>2.2f||Math.abs(mag-baseline)>8f);long now=System.currentTimeMillis();if(active){lastDetected=now;rotor.running=true;rotor.invalidate();state.setText("✓ Activité magnétique détectée");state.setTextColor(GREEN);state.setBackground(box(Color.rgb(235,251,240),16));if(now-lastFeedback>1800){lastFeedback=now;if(sound)tone.startTone(ToneGenerator.TONE_PROP_BEEP,90);if(vibration){Vibrator vb=(Vibrator)getSystemService(VIBRATOR_SERVICE);if(Build.VERSION.SDK_INT>=26)vb.vibrate(VibrationEffect.createOneShot(80,VibrationEffect.DEFAULT_AMPLITUDE));else vb.vibrate(80);}}}else if(now-lastDetected>1200){rotor.running=false;rotor.invalidate();state.setText("✕ Aucune activité détectée");state.setTextColor(RED);state.setBackground(box(Color.rgb(255,241,241),16));}}
 @Override public void onAccuracyChanged(Sensor s,int a){} String time(int s){return String.format(Locale.FRANCE,"%02d:%02d",s/60,s%60);} @Override protected void onPause(){super.onPause();if(sm!=null)sm.unregisterListener(this);} @Override protected void onResume(){super.onResume();if(magnetic!=null&&rotor!=null)sm.registerListener(this,magnetic,SensorManager.SENSOR_DELAY_GAME);}
 static class RotorView extends View{Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);boolean running;float angle;RotorView(Context c){super(c);}protected void onDraw(Canvas c){super.onDraw(c);float cx=getWidth()/2f,cy=getHeight()/2f,r=Math.min(getWidth(),getHeight())*.37f;p.setColor(NAVY);c.drawCircle(cx,cy,r,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(Math.max(2,r*.035f));p.setColor(Color.rgb(75,103,130));c.drawCircle(cx,cy,r*.86f,p);p.setStyle(Paint.Style.FILL);c.save();c.rotate(angle,cx,cy);p.setColor(running?ORANGE:Color.rgb(80,98,116));for(int i=0;i<5;i++){c.save();c.rotate(i*72,cx,cy);RectF q=new RectF(cx-r*.10f,cy-r*.70f,cx+r*.34f,cy-r*.10f);c.drawOval(q,p);c.restore();}c.restore();p.setColor(Color.LTGRAY);c.drawCircle(cx,cy,r*.14f,p);p.setColor(NAVY);c.drawCircle(cx,cy,r*.055f,p);if(running){angle+=12;postInvalidateDelayed(32);}}}
}
